$(document).ready(function(){
    $(".designA").click(function(){
        $(".designA").hide();
        $(".designB").toggle();
    })
})
$(document).ready(function(){
    $(".designB").click(function(){
        $(".designB").hide();
        $(".designA").toggle();
    })
})
$(document).ready(function(){
    $("#devA").click(function(){
        $("#devA").hide();
        $("#devB").toggle();
        })
    }
)
$(document).ready(function(){
    $("#devB").click(function(){
        $("#devB").hide();
        $("#devA").toggle();
        })
    }
)
$(document).ready(function(){
    $(".prodA").click(function(){
        $(".prodA").hide();
        $(".prodB").toggle();
    })
})
$(document).ready(function(){
    $(".prodB").click(function(){
        $(".prodB").hide();
        $(".prodA").toggle();
    })
})